# Generated by Django 4.2.4 on 2023-09-25 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automanage', '0002_cotizaciones_inventariopiezas_inventariovehiculos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'cotizaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioPieza',
            fields=[
                ('id_inventario_piezas', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario_piezas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioVehiculo',
            fields=[
                ('id_inventario_vehiculos', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(blank=True, max_length=10, null=True)),
                ('condicion', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'inventario_vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('valor_mano_obra', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'ordenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('serie', models.CharField(blank=True, max_length=80, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'piezas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PiezasVehiculo',
            fields=[
                ('id_pieza_vehiculo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'piezas_vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sucursales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('linea', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=180, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'vehiculos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('id_inventario_vehiculo', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cotizaciones',
        ),
        migrations.DeleteModel(
            name='InventarioPiezas',
        ),
        migrations.DeleteModel(
            name='InventarioVehiculos',
        ),
        migrations.DeleteModel(
            name='Ordenes',
        ),
        migrations.RemoveField(
            model_name='ordenpiezas',
            name='id_pieza',
        ),
        migrations.RemoveField(
            model_name='piezasvehiculos',
            name='id_vehiculo',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Sucursales',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
        migrations.CreateModel(
            name='OrdenPieza',
            fields=[
                ('id_pieza', models.OneToOneField(db_column='id_pieza', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='automanage.pieza')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'orden_piezas',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='OrdenPiezas',
        ),
        migrations.DeleteModel(
            name='Piezas',
        ),
        migrations.DeleteModel(
            name='PiezasVehiculos',
        ),
        migrations.DeleteModel(
            name='Vehiculos',
        ),
    ]
