# Generated by Django 4.2.4 on 2023-10-08 23:51

import automanage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(blank=True, max_length=25, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
            managers=[
                ('objects', automanage.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cotizacion_id_cliente_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cotizaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InventarioVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=10, null=True)),
                ('condicion', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('kilometraje', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario_vehiculos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('serie', models.CharField(blank=True, max_length=80, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'piezas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sucursales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('linea', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=180, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'vehiculos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ventas_id_cliente_set', to=settings.AUTH_USER_MODEL)),
                ('cotizacion', models.ForeignKey(blank=True, db_column='id_cotizacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.cotizacion')),
                ('inventario_vehiculo', models.ForeignKey(db_column='id_inventario_vehiculos', on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.inventariovehiculo')),
                ('vendedor', models.ForeignKey(db_column='id_vendedor', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ventas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(blank=True, max_length=10, null=True)),
                ('valor_mano_obra', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('estado', models.CharField(blank=True, max_length=150)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordenes_id_cliente_set', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.sucursal')),
                ('vendedor', models.ForeignKey(db_column='id_vendedor', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordenes',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='inventariovehiculo',
            name='sucursal',
            field=models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.sucursal'),
        ),
        migrations.AddField(
            model_name='inventariovehiculo',
            name='vehiculo',
            field=models.ForeignKey(blank=True, db_column='id_vehiculo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.vehiculo'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='inventario_vehiculos',
            field=models.ForeignKey(db_column='id_inventario_vehiculos', on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.inventariovehiculo'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vendedor',
            field=models.ForeignKey(db_column='id_vendedor', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='PiezasVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza', models.ForeignKey(db_column='id_pieza', on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.pieza')),
                ('vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.vehiculo')),
            ],
            options={
                'db_table': 'piezas_vehiculos',
                'managed': True,
                'unique_together': {('vehiculo', 'pieza')},
            },
        ),
        migrations.CreateModel(
            name='OrdenPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.orden')),
                ('pieza', models.ForeignKey(db_column='id_pieza', on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.pieza')),
            ],
            options={
                'db_table': 'orden_piezas',
                'managed': True,
                'unique_together': {('orden', 'pieza')},
            },
        ),
        migrations.CreateModel(
            name='InventarioPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.IntegerField(blank=True, null=True)),
                ('pieza', models.ForeignKey(db_column='id_pieza', on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.pieza')),
                ('sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.sucursal')),
            ],
            options={
                'db_table': 'inventario_piezas',
                'managed': True,
                'unique_together': {('pieza', 'sucursal')},
            },
        ),
    ]
