# Generated by Django 4.2.4 on 2023-10-21 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.sucursal'),
        ),
    ]
