# Generated by Django 4.2.4 on 2023-11-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automanage', '0004_alter_usuario_identificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariovehiculo',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
