# Generated by Django 4.2.4 on 2023-11-18 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automanage', '0005_inventariovehiculo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariovehiculo',
            name='vehiculo',
            field=models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.DO_NOTHING, to='automanage.vehiculo'),
        ),
    ]
