# Generated by Django 4.2.4 on 2023-11-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automanage', '0006_alter_inventariovehiculo_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
